name: "Group Project"
navbar:
  title: "Forest Fire"
  left:
    - text: "Introduction"
      href: introduction.html
    - text: "BST260_group_project"
      href: BST260_group_project.html

theme: jekyll-theme-cayman